server:
  port: 80

eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka

ribbon:
  # 建立连接所用的时间
  ConnectTimeout: 5000
  # 读取数据所用的时间
  ReadTimeout: 5000

  # OpenFeign的底层其实就是 Robbin + http 协议
  # Robbin用于负载均衡和服务发现，Http用于网络连接
  # 在 OpenFeign 内，默认的连接、读取服务时间的时间是 1s,这是由Robbin规定的
  # 所以我们可以通过设置Robbin的连接时间和读取数据的时间从而控制OpenFeign的连接超时